import type { Metadata } from "next";
import { Mulish } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";

const mulish = Mulish({ weight: "400", subsets: ["latin"], display: "swap" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={mulish.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
